displayName=Dorgesh-Kaan Agility Course Helper
author=Toothless
description=Provides helpful information for the Dorgesh-Kaan Agility Course
tags=agility,course,helper,dorgesh-kaan,dorgesh,kaan,dorgeshkaan
version=
plugins=uk.zadoss.dorgesh.agility.DorgeshKaanAgility
build=standard